project:
  type: book

book:
  title: "Cofit x Genesis 醫療大數據（分析報告）"
  author: "Clover Teoh"
  chapters:
    - index.qmd
    - 1.1 疾病診斷標準.qmd
    - 5 亞健康改善成效.qmd

format: 
 html:
    theme: cosmo
    number-sections: false
    heading-anchors: false # 關閉標題自帶的錨點連結（anchor links）
    toc: false
    grid:
     sidebar-width: 200px
     body-width: 900px

  

