project:
  type: book

book:
  title: "Cofit x Genesis 醫療大數據（分析報告）"
  author: "Clover Teoh"
  chapters:
    - index.qmd
    - 1.1 疾病診斷標準.qmd
    - 1.2 客戶輪廓分析.qmd
    - 1.2_1 客戶輪廓分析.qmd
    - 1.3 整體成效分析.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    toc: false
    grid:
     sidebar-width: 300px
     body-width: 900px

